# Autograd package in PyTorch

In [1]:
import numpy as np
import torch 

In [9]:
# x requires the gradient
x = torch.randn(3, requires_grad=True)
y = x + 2
print("Tensor y is:", y)
z = y*y*2
print("Tensor z is:", z)
z = z.mean()
print("Tensor z is:", z)

Tensor y is: tensor([3.6201, 2.2130, 1.5203], grad_fn=<AddBackward0>)
Tensor z is: tensor([26.2109,  9.7951,  4.6228], grad_fn=<MulBackward0>)
Tensor z is: tensor(13.5430, grad_fn=<MeanBackward0>)


In [10]:
z.backward() # dz/dx
x.grad

tensor([4.8269, 2.9507, 2.0271])

In [17]:
a = torch.randn(3, requires_grad=True)
print(a)
b = a + 2
c = b * b * 2

# It's a Jacobian matrix times a Tensor
a_ = torch.tensor([1,1,1], dtype = torch.float32)
c.backward(a_)

tensor([ 0.7965, -0.1738, -0.3446], requires_grad=True)


In [23]:
x = torch.randn(3, requires_grad=True)
print(x)

# change the requires_grad_ of x to False
# x.requires_grad_(False)

# create a copy of x that doesn't require the gradient
# y = x.detach()
# print(y)

# stop PyTorch the gradient issue 
with torch.no_grad():
    y = x + 2
    print(y)

tensor([-0.2978,  1.1208,  1.9581], requires_grad=True)
tensor([1.7022, 3.1208, 3.9581])


In [28]:
# set the requires_grad to True
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):

    model_output = (weights * 3).sum()
    
    # calculate gradient
    model_output.backward()
    print(weights.grad)

    # clear the gradients before doing the next iteration
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
